const src = {
  // pick imgs from the dom

  allImgs: [],
  allImgsDom: document.querySelectorAll(".main-window-imgs"),
  allVideosDom: document.querySelectorAll(".main-window-videos"),
  set() {
    this.allItems = {
      arrowRound: this.allImgsDom[0],
      blinkArrow: this.allImgsDom[1],
      laerrow: this.allImgsDom[2],
      laerrow2: this.allImgsDom[3],
      logo: this.allImgsDom[4],
      man: this.allImgsDom[5],
      measurearrow: this.allImgsDom[6],
      measurearrow2: this.allImgsDom[7],
      redsize: this.allImgsDom[8],                                         
      speech_off_btn: this.allImgsDom[9],
      speech_on_btn: this.allImgsDom[10],
      talk_cloud: this.allImgsDom[11],
      iit_delhi_logo: this.allImgsDom[12],

      
left_aluminium1:this.allImgsDom[13],
left_aluminium2:this.allImgsDom[14],
left_base_plate1:this.allImgsDom[15],
left_base_plate2:this.allImgsDom[16],
left_base_plate3:this.allImgsDom[17],
left_base_plate4:this.allImgsDom[18],
left_beam1:this.allImgsDom[19],
left_beam1_left:this.allImgsDom[20],
left_beam1_right:this.allImgsDom[21],
left_beam2:this.allImgsDom[22],
left_beam2_left:this.allImgsDom[23],
left_beam2_right:this.allImgsDom[24],
left_beam3:this.allImgsDom[25],
left_beam4:this.allImgsDom[26],
left_beam5:this.allImgsDom[27],
left_beam6:this.allImgsDom[28],
left_bfs1_left:this.allImgsDom[29],
left_bfs1_right:this.allImgsDom[30],
left_bfs2_left:this.allImgsDom[31],
left_bfs2_right:this.allImgsDom[32],
left_bfs3_left:this.allImgsDom[33],
left_bfs3_right:this.allImgsDom[34],
left_ct_prop1:this.allImgsDom[35],
left_ct_prop2:this.allImgsDom[36],
left_ct_prop3:this.allImgsDom[37],
left_ct_prop4:this.allImgsDom[38],
left_sheathing1:this.allImgsDom[39],
left_sheathing_left:this.allImgsDom[40],
left_sheathing_right:this.allImgsDom[41],
left_uhead1:this.allImgsDom[42],
left_uhead2:this.allImgsDom[43],
left_uhead3:this.allImgsDom[44],
left_uhead4:this.allImgsDom[45],
right_aluminium1:this.allImgsDom[46],
right_aluminium2:this.allImgsDom[47],
right_base_plate1:this.allImgsDom[48],
right_base_plate2:this.allImgsDom[49],
right_base_plate3:this.allImgsDom[50],
right_base_plate4:this.allImgsDom[51],
right_beam1:this.allImgsDom[52],
right_beam2:this.allImgsDom[53],
right_beam3:this.allImgsDom[54],
right_beam4:this.allImgsDom[55],
right_beam5:this.allImgsDom[56],
right_beam6:this.allImgsDom[57],
right_beam_left1:this.allImgsDom[58],
right_beam_left2:this.allImgsDom[59],
right_beam_right1:this.allImgsDom[60],
right_beam_right2:this.allImgsDom[61],
right_bfs_left1:this.allImgsDom[62],
right_bfs_left2:this.allImgsDom[63],
right_bfs_left3:this.allImgsDom[64],
right_bfs_right1:this.allImgsDom[65],
right_bfs_right2:this.allImgsDom[66],
right_bfs_right3:this.allImgsDom[67],
right_ct_prop1:this.allImgsDom[68],
right_ct_prop2:this.allImgsDom[69],
right_ct_prop3:this.allImgsDom[70],
right_ct_prop4:this.allImgsDom[71],
right_sheathing1:this.allImgsDom[72],
right_sheathing_left:this.allImgsDom[73],
right_sheathing_right:this.allImgsDom[74],
right_u_head1:this.allImgsDom[75],
right_u_head2:this.allImgsDom[76],
right_u_head3:this.allImgsDom[77],
right_u_head4:this.allImgsDom[78],
slab_aluminium1:this.allImgsDom[79],
slab_aluminium2:this.allImgsDom[80],
slab_beam1:this.allImgsDom[81],
slab_beam2:this.allImgsDom[82],
slab_beam3:this.allImgsDom[83],
slab_beam4:this.allImgsDom[84],
slab_beam5:this.allImgsDom[85],
slab_ct_prop1:this.allImgsDom[86],
slab_ct_prop2:this.allImgsDom[87],
slab_ct_prop3:this.allImgsDom[88],
slab_ct_prop4:this.allImgsDom[89],
slab_sheathing1:this.allImgsDom[90],
slab_uhead1:this.allImgsDom[91],
slab_uhead2:this.allImgsDom[92],
slab_uhead3:this.allImgsDom[93],
slab_uhead4:this.allImgsDom[94],
slab_u_head1:this.allImgsDom[95],
left_sheathing1_nail1:this.allImgsDom[96],
left_sheathing1_nail2:this.allImgsDom[97],
left_sheathing1_nail3:this.allImgsDom[98],
left_sheathing1_nail4:this.allImgsDom[99],
left_sheathing1_nail_helper:this.allImgsDom[100],
right_sheathing1_nail1:this.allImgsDom[101],
right_sheathing1_nail2:this.allImgsDom[102],
right_sheathing1_nail3:this.allImgsDom[103],
right_sheathing1_nail4:this.allImgsDom[104],
right_sheathing1_nail_helper:this.allImgsDom[105],
hammer:this.allImgsDom[106],
objective:this.allImgsDom[107],
left_bracing1:this.allImgsDom[108],
left_bracing10:this.allImgsDom[109],
left_bracing2:this.allImgsDom[110],
left_bracing3:this.allImgsDom[111],
left_bracing4:this.allImgsDom[112],
left_bracing5:this.allImgsDom[113],
left_bracing6:this.allImgsDom[114],
left_bracing7:this.allImgsDom[115],
left_bracing8:this.allImgsDom[116],
left_bracing9:this.allImgsDom[117],
right_bracing1:this.allImgsDom[118],
right_bracing10:this.allImgsDom[119],
right_bracing2:this.allImgsDom[120],
right_bracing3:this.allImgsDom[121],
right_bracing4:this.allImgsDom[122],
right_bracing5:this.allImgsDom[123],
right_bracing6:this.allImgsDom[124],
right_bracing7:this.allImgsDom[125],
right_bracing8:this.allImgsDom[126],
right_bracing9:this.allImgsDom[127],


      
      
      
      // * Videos
      // yoke_front_to_back: this.allVideosDom[0],
      // yoke_front_to_side: this.allVideosDom[1],
      // panel1: this.allVideosDom[2],
      // panel2: this.allVideosDom[3],

      bfs_video: this.allVideosDom[0],
    };
  },
  allImgsInitialAxis: [],
  get(itemName) {
    return this.allItems[itemName];
  },
};
// setting src
src.set();
